report:
  title: "MicW2Graph"
  description: >
    Wastewater treatment (WWT) is the process of removing contaminants from used water before it is discharged back 
    into the environment, which contributes to address water scarcity and to protect aquatic ecosystems. In this project, 
    we investigated the microbiome of WWT to build MicW2Graph, an open-source knowledge graph (KG) that integrates metagenomic and 
    metatranscriptomic information with their biological context, including biological processes, environmental and phenotypic 
    features, chemical compounds, and additional metadata. We developed a workflow to collect meta-omics datasets from MGnify and 
    infer potential interactions among microorganisms through microbial association networks (MANs). MicW2Graph enables the 
    investigation of research questions related to WWT, focusing on aspects such as microbial connections, community memberships, 
    and potential ecological functions.
  graphical_abstract: "example_data/MicW2Graph/Methods_MicW2Graph.png"
  logo: "example_data/mona_logo.png"
sections:
  - title: "Exploratory Data Analysis"
    subsections:
      - title: "Abundance data"
        description: "Optional description"
        components:
          - title: "Top 5 species by biome (plotly)"
            component_type: "plot"
            plot_type: "plotly"
            file_path: "example_data/MicW2Graph/top_species_plot_biome.json"
            caption: "Optional caption"
          - title: "Multiline plot (altair)"
            component_type: "plot"
            plot_type: "altair"
            file_path: "example_data/altair_multilineplot.json"
          - title: "Abundance data for all studies (csv)"
            component_type: "dataframe"
            file_path: "example_data/MicW2Graph/abundance_data_allbiomes.csv"
            file_format: "csv"
            delimiter: ","
          - title: "Abundance data for all studies (excel)"
            component_type: "dataframe"
            file_path: "example_data/MicW2Graph/abundance_data_allbiomes.xls"
            file_format: "excel"
            delimiter: ","
      - title: "Sample data"
        components:
          - title: "Number of samples per study (png)"
            component_type: "plot"
            plot_type: "static"
            file_path: "example_data/MicW2Graph/number_samples_per_study.png"
          - title: "Sampling countries for all studies (plotly)"
            component_type: "plot"
            plot_type: "plotly"
            file_path: "example_data/MicW2Graph/pie_plot_countries.json"
          - title: "Sample data for all studies (txt)"
            component_type: "dataframe"
            file_path: "example_data/MicW2Graph/sample_info_allbiomes.txt"
            file_format: "txt"
          - title: "Sample data for all studies (parquet)"
            component_type: "dataframe"
            file_path: "example_data/MicW2Graph/sample_info_allbiomes.parquet"
            file_format: "parquet"
      - title: "Extra information"
        components:
          - title: "Markdown example"
            component_type: "markdown"
            file_path: "example_data/test_md.md"
  - title: "Microbial Association Networks"
    subsections:
      - title: "Network Visualization1"
        components:
          - title: "Network1 (graphml)"
            component_type: "plot"
            plot_type: "interactive_network"
            file_path: "example_data/MicW2Graph/man_example.graphml"
      - title: "Network Visualization2"
        components:
          - title: "Network2 (edge list csv)"
            component_type: "plot"
            plot_type: "interactive_network"
            csv_network_format: "edgelist"
            file_path: "example_data/MicW2Graph/man_example.csv"
      - title: "Edge list"
        components:
          - title: "Edge list (csv)"
            component_type: "dataframe"
            file_path: "example_data/MicW2Graph/man_example.csv"
            file_format: "csv"
            delimiter: ","
            caption: "This is the edge list of the network"
  - title: "APICall test"
    subsections:
      - title: "Simple test"
        components:
          - title: "APICall test"
            component_type: "apicall"
            api_url: "https://jsonplaceholder.typicode.com/todos/1"
