report:
  title: Micw2Graph
  description: 'Wastewater treatment (WWT) is the process of removing contaminants
    from used water before it is discharged back into the environment, which contributes
    to address water scarcity and to protect aquatic ecosystems. In this project,
    we investigated the microbiome of WWT to build MicW2Graph, an open-source knowledge
    graph (KG) that integrates metagenomic and metatranscriptomic information with
    their biological context, including biological processes, environmental and phenotypic
    features, chemical compounds, and additional metadata. We developed a workflow
    to collect meta-omics datasets from MGnify and infer potential interactions among
    microorganisms through microbial association networks (MANs). MicW2Graph enables
    the investigation of research questions related to WWT, focusing on aspects such
    as microbial connections, community memberships, and potential ecological functions.

    '
  graphical_abstract: ''
  logo: ''
sections:
- title: Exploratory Data Analysis
  description: ''
  subsections:
  - title: Abundance Data
    description: 'Optional description for section.

      '
    components:
    - component_type: plot
      plot_type: plotly
      title: Top Species Plot Biome
      file_path: /Users/asaru/Documents/DTU/MoNA/vuegen/docs/example_data/MicW2Graph/1_Exploratory_Data_Analysis/1_Abundance_data/1_top_species_plot_biome.json
      description: ''
    - component_type: plot
      plot_type: altair
      title: Multilineplot
      file_path: /Users/asaru/Documents/DTU/MoNA/vuegen/docs/example_data/MicW2Graph/1_Exploratory_Data_Analysis/1_Abundance_data/2_multilineplot.json
      description: ''
    - component_type: dataframe
      file_format: csv
      delimiter: ','
      title: Abundance Data Allbiomes
      file_path: /Users/asaru/Documents/DTU/MoNA/vuegen/docs/example_data/MicW2Graph/1_Exploratory_Data_Analysis/1_Abundance_data/3_abundance_data_allbiomes.csv
      description: ''
    - component_type: dataframe
      file_format: xls
      title: Abundance Data Allbiomes
      file_path: /Users/asaru/Documents/DTU/MoNA/vuegen/docs/example_data/MicW2Graph/1_Exploratory_Data_Analysis/1_Abundance_data/4_abundance_data_allbiomes.xls
      description: ''
    - component_type: markdown
      title: Description
      file_path: /Users/asaru/Documents/DTU/MoNA/vuegen/docs/example_data/MicW2Graph/1_Exploratory_Data_Analysis/1_Abundance_data/description.md
      description: ''
  - title: Sample Data
    description: ''
    components:
    - component_type: plot
      plot_type: plotly
      title: Pie Plot Countries Plotly
      file_path: /Users/asaru/Documents/DTU/MoNA/vuegen/docs/example_data/MicW2Graph/1_Exploratory_Data_Analysis/2_Sample_data/1_pie_plot_countries_plotly.json
      description: ''
    - component_type: plot
      plot_type: plotly
      title: Pie Plots Biomes Plotly
      file_path: /Users/asaru/Documents/DTU/MoNA/vuegen/docs/example_data/MicW2Graph/1_Exploratory_Data_Analysis/2_Sample_data/2_pie_plots_biomes_plotly.json
      description: ''
    - component_type: plot
      plot_type: static
      title: Number Samples Per Study
      file_path: /Users/asaru/Documents/DTU/MoNA/vuegen/docs/example_data/MicW2Graph/1_Exploratory_Data_Analysis/2_Sample_data/3_number_samples_per_study.png
      description: ''
    - component_type: dataframe
      file_format: parquet
      title: Sample Info Allbiomes
      file_path: /Users/asaru/Documents/DTU/MoNA/vuegen/docs/example_data/MicW2Graph/1_Exploratory_Data_Analysis/2_Sample_data/4_sample_info_allbiomes.parquet
      description: ''
    - component_type: dataframe
      file_format: txt
      delimiter: \t
      title: Sample Info Allbiomes
      file_path: /Users/asaru/Documents/DTU/MoNA/vuegen/docs/example_data/MicW2Graph/1_Exploratory_Data_Analysis/2_Sample_data/5_sample_info_allbiomes.txt
      description: ''
  - title: Extra Info
    description: ''
    components:
    - component_type: markdown
      title: Test Md
      file_path: /Users/asaru/Documents/DTU/MoNA/vuegen/docs/example_data/MicW2Graph/1_Exploratory_Data_Analysis/3_Extra_info/1_test_md.md
      description: ''
    - component_type: html
      title: Plot
      file_path: /Users/asaru/Documents/DTU/MoNA/vuegen/docs/example_data/MicW2Graph/1_Exploratory_Data_Analysis/3_Extra_info/plot.html
      description: ''
- title: Microbial Association Networks
  description: ''
  subsections:
  - title: Network Visualization1
    description: 'Optional description for subsection.

      '
    components:
    - component_type: plot
      plot_type: interactive_network
      title: Man Example
      file_path: /Users/asaru/Documents/DTU/MoNA/vuegen/docs/example_data/MicW2Graph/2_Microbial_Association_Networks/1_Network_visualization1/1_man_example.graphml
      description: ''
    - component_type: markdown
      title: Description
      file_path: /Users/asaru/Documents/DTU/MoNA/vuegen/docs/example_data/MicW2Graph/2_Microbial_Association_Networks/1_Network_visualization1/description.md
      description: ''
  - title: Network Visualization2
    description: ''
    components:
    - component_type: plot
      plot_type: interactive_network
      csv_network_format: edgelist
      title: Man Example Edgelist
      file_path: /Users/asaru/Documents/DTU/MoNA/vuegen/docs/example_data/MicW2Graph/2_Microbial_Association_Networks/2_Network_visualization2/1_man_example_edgelist.csv
      description: ''
  - title: Network Visualization3
    description: ''
    components:
    - component_type: plot
      plot_type: interactive_network
      title: Man Example
      file_path: /Users/asaru/Documents/DTU/MoNA/vuegen/docs/example_data/MicW2Graph/2_Microbial_Association_Networks/3_Network_visualization3/1_man_example.cyjs
      description: ''
  - title: Network Visualization4
    description: ''
    components:
    - component_type: plot
      plot_type: interactive_network
      title: Ckg Network
      file_path: /Users/asaru/Documents/DTU/MoNA/vuegen/docs/example_data/MicW2Graph/2_Microbial_Association_Networks/4_Network_visualization4/1_ckg_network.html
      description: ''
