report:
  title: MicW2Graph
  description: >
    Wastewater treatment (WWT) is the process of removing contaminants from used water before it is discharged back 
    into the environment, which contributes to address water scarcity and to protect aquatic ecosystems. In this project, 
    we investigated the microbiome of WWT to build MicW2Graph, an open-source knowledge graph (KG) that integrates metagenomic and 
    metatranscriptomic information with their biological context, including biological processes, environmental and phenotypic 
    features, chemical compounds, and additional metadata. We developed a workflow to collect meta-omics datasets from MGnify and 
    infer potential interactions among microorganisms through microbial association networks (MANs). MicW2Graph enables the 
    investigation of research questions related to WWT, focusing on aspects such as microbial connections, community memberships, 
    and potential ecological functions.
  graphical_abstract: docs/example_data/MicW2Graph/Methods_MicW2Graph.png
  logo: docs/images/vuegen_logo.png
sections:
  - title: Exploratory Data Analysis
    subsections:
      - title: Abundance data
        description: Optional description
        components:
          - title: Top 5 species by biome (plotly)
            component_type: plot
            plot_type: plotly
            file_path: https://raw.githubusercontent.com/sayalaruano/report_generator_st_cloud_test/main/example_data/MicW2Graph/top_species_plot_biome.json
            caption: Optional caption
          - title: Multiline plot (altair)
            component_type: plot
            plot_type: altair
            file_path: docs/example_data/MicW2Graph/1_Exploratory_Data_Analysis/1_Abundance_data/2_multilineplot_altair.json
          - title: Abundance data for all studies (csv)
            component_type: dataframe
            file_path: https://raw.githubusercontent.com/sayalaruano/report_generator_st_cloud_test/main/example_data/MicW2Graph/abundance_data_allbiomes.csv
            file_format: csv
            delimiter: ','
          - title: Abundance data for all studies (xls)
            component_type: dataframe
            file_path: docs/example_data/MicW2Graph/1_Exploratory_Data_Analysis/1_Abundance_data/4_abundance_data_allbiomes.xls
            file_format: xls
            delimiter: ','
      - title: Sample data
        components:
          - title: Number of samples per study (png)
            component_type: plot
            plot_type: static
            file_path: docs/example_data/MicW2Graph/1_Exploratory_Data_Analysis/2_Sample_data/3_number_samples_per_study.png
          - title: Sampling countries for all studies (plotly)
            component_type: plot
            plot_type: plotly
            file_path: docs/example_data/MicW2Graph/1_Exploratory_Data_Analysis/2_Sample_data/1_pie_plot_countries_plotly.json
          - title: Sample data for all studies (parquet)
            component_type: dataframe
            file_path: docs/example_data/MicW2Graph/1_Exploratory_Data_Analysis/2_Sample_data/4_sample_info_allbiomes.parquet
            file_format: parquet
          - title: Sample data for all studies (txt)
            component_type: dataframe
            file_path: docs/example_data/MicW2Graph/1_Exploratory_Data_Analysis/2_Sample_data/5_sample_info_allbiomes.txt
            file_format: txt
      - title: Extra information
        components:
          - title: Markdown example
            component_type: markdown
            file_path: https://raw.githubusercontent.com/sayalaruano/report_generator_st_cloud_test/main/example_data/test_md.md
  - title: Microbial Association Networks
    subsections:
      - title: Network Visualization1
        components:
          - title: Network1 (graphml)
            component_type: plot
            plot_type: interactive_network
            file_path: docs/example_data/MicW2Graph/2_Microbial_Association_Networks/1_Network_visualization1/1_man_example.graphml
      - title: Network Visualization2
        components:
          - title: Network2 (edge list csv)
            component_type: plot
            plot_type: interactive_network
            csv_network_format: edgelist
            file_path: docs/example_data/MicW2Graph/2_Microbial_Association_Networks/2_Network_visualization2/1_man_example_edgelist.csv
          - title: Edge list (csv)
            component_type: dataframe
            file_path: docs/example_data/MicW2Graph/2_Microbial_Association_Networks/2_Network_visualization2/1_man_example_edgelist.csv
            file_format: csv
            delimiter: ','
            caption: This is the edge list of the network
      - title: Network Visualization3
        components:
          - title: Network3 (cyjs)
            component_type: plot
            plot_type: interactive_network
            file_path: docs/example_data/MicW2Graph/2_Microbial_Association_Networks/3_Network_visualization3/1_man_example.cyjs
      - title: Network Visualization4
        components:
          - title: Network4 (html)
            component_type: plot
            plot_type: interactive_network
            file_path: docs/example_data/MicW2Graph/2_Microbial_Association_Networks/4_Network_visualization4/1_ckg_network.html
      - title: Network Visualization5
        components:
          - title: Network5 (remote html)
            component_type: plot
            plot_type: interactive_network
            file_path: https://rawcdn.githack.com/sayalaruano/report_generator_st_cloud_test/62a9ceec2281c54b55e99017f2bddc954e7db311/example_data/network1.html
  - title: ChatBot test
    subsections:
      - title: Simple test
        components:
          - title: ChatBot test
            component_type: chatbot
            api_url: http://localhost:11434/api/chat
            model: llama3.2
