report:
  title: Micw2Graph
  description: ''
  graphical_abstract: ''
  logo: ''
sections:
- title: Exploratory Data Analysis
  description: ''
  subsections:
  - title: Abundance Data
    description: ''
    components:
    - title: Top Species Plot Biome Plotly
      file_path: /Users/asaru/Documents/DTU/MoNA/vuegen/example_data/MicW2Graph/1_Exploratory_Data_Analysis/1_Abundance_data/1_top_species_plot_biome_plotly.json
      description: ''
      component_type: plot
      plot_type: plotly
    - title: Multilineplot Altair
      file_path: /Users/asaru/Documents/DTU/MoNA/vuegen/example_data/MicW2Graph/1_Exploratory_Data_Analysis/1_Abundance_data/2_multilineplot_altair.json
      description: ''
      component_type: plot
      plot_type: altair
    - title: Abundance Data Allbiomes
      file_path: /Users/asaru/Documents/DTU/MoNA/vuegen/example_data/MicW2Graph/1_Exploratory_Data_Analysis/1_Abundance_data/3_abundance_data_allbiomes.csv
      description: ''
      component_type: dataframe
      file_format: csv
      delimiter: ','
    - title: Abundance Data Allbiomes
      file_path: /Users/asaru/Documents/DTU/MoNA/vuegen/example_data/MicW2Graph/1_Exploratory_Data_Analysis/1_Abundance_data/4_abundance_data_allbiomes.xls
      description: ''
      component_type: dataframe
      file_format: xls
  - title: Sample Data
    description: ''
    components:
    - title: Pie Plot Countries Plotly
      file_path: /Users/asaru/Documents/DTU/MoNA/vuegen/example_data/MicW2Graph/1_Exploratory_Data_Analysis/2_Sample_data/1_pie_plot_countries_plotly.json
      description: ''
      component_type: plot
      plot_type: plotly
    - title: Pie Plots Biomes Plotly
      file_path: /Users/asaru/Documents/DTU/MoNA/vuegen/example_data/MicW2Graph/1_Exploratory_Data_Analysis/2_Sample_data/2_pie_plots_biomes_plotly.json
      description: ''
      component_type: plot
      plot_type: plotly
    - title: Number Samples Per Study
      file_path: /Users/asaru/Documents/DTU/MoNA/vuegen/example_data/MicW2Graph/1_Exploratory_Data_Analysis/2_Sample_data/3_number_samples_per_study.png
      description: ''
      component_type: plot
      plot_type: static
    - title: Sample Info Allbiomes
      file_path: /Users/asaru/Documents/DTU/MoNA/vuegen/example_data/MicW2Graph/1_Exploratory_Data_Analysis/2_Sample_data/4_sample_info_allbiomes.parquet
      description: ''
      component_type: dataframe
      file_format: parquet
    - title: Sample Info Allbiomes
      file_path: /Users/asaru/Documents/DTU/MoNA/vuegen/example_data/MicW2Graph/1_Exploratory_Data_Analysis/2_Sample_data/5_sample_info_allbiomes.txt
      description: ''
      component_type: dataframe
      file_format: txt
      delimiter: \t
  - title: Extra Info
    description: ''
    components:
    - title: Test Md
      file_path: /Users/asaru/Documents/DTU/MoNA/vuegen/example_data/MicW2Graph/1_Exploratory_Data_Analysis/3_Extra_info/1_test_md.md
      description: ''
      component_type: markdown
- title: Microbial Association Networks
  description: ''
  subsections:
  - title: Network Visualization1
    description: ''
    components:
    - title: Man Example
      file_path: /Users/asaru/Documents/DTU/MoNA/vuegen/example_data/MicW2Graph/2_Microbial_Association_Networks/1_Network_visualization1/1_man_example.graphml
      description: ''
      component_type: plot
      plot_type: interactive_network
  - title: Network Visualization2
    description: ''
    components:
    - title: Man Example Edgelist
      file_path: /Users/asaru/Documents/DTU/MoNA/vuegen/example_data/MicW2Graph/2_Microbial_Association_Networks/2_Network_visualization2/1_man_example_edgelist.csv
      description: ''
      component_type: plot
      plot_type: interactive_network
      csv_network_format: edgelist
  - title: Network Visualization3
    description: ''
    components:
    - title: Man Example
      file_path: /Users/asaru/Documents/DTU/MoNA/vuegen/example_data/MicW2Graph/2_Microbial_Association_Networks/3_Network_visualization3/1_man_example.cyjs
      description: ''
      component_type: plot
      plot_type: interactive_network
  - title: Network Visualization4
    description: ''
    components:
    - title: Ckg Network
      file_path: /Users/asaru/Documents/DTU/MoNA/vuegen/example_data/MicW2Graph/2_Microbial_Association_Networks/4_Network_visualization4/1_ckg_network.html
      description: ''
      component_type: plot
      plot_type: interactive_network
