name: Test documentation building (until it's moved to ReadTheDocs)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]
    
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip' # caching pip dependencies
          cache-dependency-path: '**/pyproject.toml'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[docs]
      - name: Build references
        run: |
            cd docs
            sphinx-apidoc --force --implicit-namespaces --module-first -o reference ../src/vuegen
      - name: Build documentation
        run: |
            cd docs
            sphinx-build -n --keep-going -b html ./ ./_build/
      # - name: save artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: Sphinx_${{ matrix.python-version }}
      #     path: docs/_build/
